# CMake generated Testfile for 
# Source directory: /home/admin1/install/aseba/aseba/tests
# Build directory: /home/admin1/install/aseba/build-aseba/tests
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(natives-count "/aseba-test-natives-count")
ADD_TEST(basic-arithmetic "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/basic-arithmetic.dump" "/home/admin1/install/aseba/aseba/tests/data/basic-arithmetic.txt")
ADD_TEST(basic-arithmetic-vector "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/basic-arithmetic-vector.dump" "/home/admin1/install/aseba/aseba/tests/data/basic-arithmetic-vector.txt")
ADD_TEST(advanced-arithmetic "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/advanced-arithmetic.dump" "/home/admin1/install/aseba/aseba/tests/data/advanced-arithmetic.txt")
ADD_TEST(advanced-arithmetic-vector "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/advanced-arithmetic-vector.dump" "/home/admin1/install/aseba/aseba/tests/data/advanced-arithmetic-vector.txt")
ADD_TEST(binary-op "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/binary-op.dump" "/home/admin1/install/aseba/aseba/tests/data/binary-op.txt")
ADD_TEST(shift-op "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/shift-op.dump" "/home/admin1/install/aseba/aseba/tests/data/shift-op.txt")
ADD_TEST(compound-assignment "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/compound-assignments.dump" "/home/admin1/install/aseba/aseba/tests/data/compound-assignments.txt")
ADD_TEST(compound-assignment-vector "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/compound-assignments-vector.dump" "/home/admin1/install/aseba/aseba/tests/data/compound-assignments-vector.txt")
ADD_TEST(binary-assignment "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/binary-assignments.dump" "/home/admin1/install/aseba/aseba/tests/data/binary-assignments.txt")
ADD_TEST(shift-assignment "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/shift-assignments.dump" "/home/admin1/install/aseba/aseba/tests/data/shift-assignments.txt")
ADD_TEST(shift-assignment-vector "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/shift-assignments-vector.dump" "/home/admin1/install/aseba/aseba/tests/data/shift-assignments-vector.txt")
ADD_TEST(multiple-logic-op "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/multiple-logic-op.dump" "/home/admin1/install/aseba/aseba/tests/data/multiple-logic-op.txt")
ADD_TEST(unicode "/asebatest" "-d" "-s" "/home/admin1/install/aseba/aseba/tests/data/unicode.txt")
ADD_TEST(optimisation-binary-not "/asebatest" "/home/admin1/install/aseba/aseba/tests/data/optimisation-binary-not.txt")
ADD_TEST(for-loop "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/for-loop.dump" "/home/admin1/install/aseba/aseba/tests/data/for-loop.txt")
ADD_TEST(for-loop-vector "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/for-loop-vector.dump" "/home/admin1/install/aseba/aseba/tests/data/for-loop-vector.txt")
ADD_TEST(while-loop "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/while-loop.dump" "/home/admin1/install/aseba/aseba/tests/data/while-loop.txt")
ADD_TEST(while-loop-vector "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/while-loop-vector.dump" "/home/admin1/install/aseba/aseba/tests/data/while-loop-vector.txt")
ADD_TEST(when-conditional "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/when-conditional.dump" "/home/admin1/install/aseba/aseba/tests/data/when-conditional.txt")
ADD_TEST(comments "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/comments.dump" "/home/admin1/install/aseba/aseba/tests/data/comments.txt")
ADD_TEST(subroutine "/asebatest" "/home/admin1/install/aseba/aseba/tests/data/subroutine.txt")
ADD_TEST(array-post-increment "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/array-post-increment.dump" "/home/admin1/install/aseba/aseba/tests/data/array-post-increment.txt")
ADD_TEST(array-constant-access "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/array-constant-access.dump" "/home/admin1/install/aseba/aseba/tests/data/array-constant-access.txt")
ADD_TEST(vardef "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/vardef.dump" "/home/admin1/install/aseba/aseba/tests/data/vardef.txt")
ADD_TEST(vardef-compat "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/vardef-compat.dump" "/home/admin1/install/aseba/aseba/tests/data/vardef-compat.txt")
ADD_TEST(vardef-constant-size "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/vardef-constant-size.dump" "/home/admin1/install/aseba/aseba/tests/data/vardef-constant-size.txt")
ADD_TEST(general-tuple "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/general-tuple.dump" "/home/admin1/install/aseba/aseba/tests/data/general-tuple.txt")
ADD_TEST(assignments "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/assignments.dump" "/home/admin1/install/aseba/aseba/tests/data/assignments.txt")
ADD_TEST(events "/asebatest" "/home/admin1/install/aseba/aseba/tests/data/events.txt")
ADD_TEST(general-tuple-events "/asebatest" "/home/admin1/install/aseba/aseba/tests/data/general-tuple-events.txt")
ADD_TEST(native-function "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/native-function.dump" "/home/admin1/install/aseba/aseba/tests/data/native-function.txt")
ADD_TEST(general-tuple-native-function "/asebatest" "/home/admin1/install/aseba/aseba/tests/data/general-tuple-native-function.txt")
ADD_TEST(var-def-compat-issue135 "/asebatest" "/home/admin1/install/aseba/aseba/tests/data/var-def-compat-issue135.txt")
ADD_TEST(array-indirect-access-issue134 "/asebatest" "--memcmp" "/home/admin1/install/aseba/aseba/tests/data/array-indirect-access-issue134.dump" "/home/admin1/install/aseba/aseba/tests/data/array-indirect-access-issue134.txt")
ADD_TEST(division-by-zero-dyn "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/division-by-zero-dyn.txt")
ADD_TEST(division-by-zero-static "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/division-by-zero-static.txt")
ADD_TEST(chained-conditional "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/chained-conditional.txt")
ADD_TEST(implicit-conditional "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/implicit-conditional.txt")
ADD_TEST(array-access-out-of-bounds-dyn-over "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-dyn-over.txt")
ADD_TEST(array-access-out-of-bounds-dyn-under "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-dyn-under.txt")
ADD_TEST(array-access-out-of-bounds-static-over "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-static-over.txt")
ADD_TEST(array-access-out-of-bounds-static-under "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-static-under.txt")
ADD_TEST(vector-access-out-of-bounds-static-over "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vector-access-out-of-bounds-static-over.txt")
ADD_TEST(vector-access-out-of-bounds-static-under "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vector-access-out-of-bounds-static-under.txt")
ADD_TEST(vector-access-two-expr "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vector-access-two-expr.txt")
ADD_TEST(assigning-bool "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/assigning-bool.txt")
ADD_TEST(inconsistent-input1 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input1.txt")
ADD_TEST(inconsistent-input2 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input2.txt")
ADD_TEST(inconsistent-input3 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input3.txt")
ADD_TEST(inconsistent-input4 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input4.txt")
ADD_TEST(assignments-fail1 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/assignments-fail1.txt")
ADD_TEST(assignments-fail2 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/assignments-fail2.txt")
ADD_TEST(assignments-fail3 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/assignments-fail3.txt")
ADD_TEST(assignments-fail4 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/assignments-fail4.txt")
ADD_TEST(vardef-fail1 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vardef-fail1.txt")
ADD_TEST(vardef-fail2 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vardef-fail2.txt")
ADD_TEST(vardef-fail3 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vardef-fail3.txt")
ADD_TEST(vardef-compat-fail1 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vardef-compat-fail1.txt")
ADD_TEST(vardef-not-constant-size "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/vardef-not-constant-size.txt")
ADD_TEST(out-of-memory1 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/out-of-memory1.txt")
ADD_TEST(out-of-memory2 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/out-of-memory2.txt")
ADD_TEST(out-of-memory-temp1 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/out-of-memory-temp1.txt")
ADD_TEST(out-of-memory-temp2 "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/out-of-memory-temp2.txt")
ADD_TEST(if-condition-vector "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/if-condition-vector.txt")
ADD_TEST(for-loop-condition-vector "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/for-loop-condition-vector.txt")
ADD_TEST(constant-namespace-collision "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/constant-namespace-collision.txt")
ADD_TEST(array-constant-access-fail "/asebatest" "--fail" "/home/admin1/install/aseba/aseba/tests/data/array-constant-access-fail.txt")
ADD_TEST(simulate-basic-arithmetic "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/basic-arithmetic.txt")
ADD_TEST(simulate-advanced-arithmetic "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/advanced-arithmetic.txt")
ADD_TEST(simulate-binary-op "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/binary-op.txt")
ADD_TEST(simulate-shift-op "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/shift-op.txt")
ADD_TEST(simulate-compound-assignment "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/compound-assignments.txt")
ADD_TEST(simulate-binary-assignment "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/binary-assignments.txt")
ADD_TEST(simulate-shift-assignment "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/shift-assignments.txt")
ADD_TEST(simulate-multiple-logic-op "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/multiple-logic-op.txt")
ADD_TEST(simulate-unicode "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/unicode.txt")
ADD_TEST(simulate-optimisation-binary-not "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/optimisation-binary-not.txt")
ADD_TEST(simulate-for-loop "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/for-loop.txt")
ADD_TEST(simulate-while-loop "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/while-loop.txt")
ADD_TEST(simulate-when-conditional "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/when-conditional.txt")
ADD_TEST(simulate-comments "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/comments.txt")
ADD_TEST(simulate-subroutine "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/subroutine.txt")
ADD_TEST(simulate-division-by-zero-dyn "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/division-by-zero-dyn.txt")
ADD_TEST(simulate-division-by-zero-static "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/division-by-zero-static.txt")
ADD_TEST(simulate-chained-conditional "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/chained-conditional.txt")
ADD_TEST(simulate-implicit-conditional "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/implicit-conditional.txt")
ADD_TEST(simulate-array-access-out-of-bounds-dyn-over "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-dyn-over.txt")
ADD_TEST(simulate-array-access-out-of-bounds-dyn-under "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-dyn-under.txt")
ADD_TEST(simulate-array-access-out-of-bounds-static-over "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-static-over.txt")
ADD_TEST(simulate-array-access-out-of-bounds-static-under "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/array-access-out-of-bounds-static-under.txt")
ADD_TEST(simulate-assigning-bool "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/assigning-bool.txt")
ADD_TEST(simulate-inconsistent-input1 "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input1.txt")
ADD_TEST(simulate-inconsistent-input2 "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input2.txt")
ADD_TEST(simulate-inconsistent-input3 "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input3.txt")
ADD_TEST(simulate-inconsistent-input4 "/home/admin1/install/aseba/aseba/tests/simulateuser.py" "/home/admin1/install/aseba/build-aseba/tests/asebatest" "/home/admin1/install/aseba/aseba/tests/data/inconsistent-input4.txt")
